### ISSUE TITLE
Button to deploy wallet

### ISSUE THREAD

**Issue by edulanasca** [Scaffold-Stark/scaffold-stark-2#200]
## Issue Overview

Currently there's only a warning that a wallet is not deployed when connected one in scaffold.

## Proposed Solutions or Ideas

Improve the warning to become a button that allows the user to deploy their wallet (make the init contract transaction).

**Comment by ooochoche** [comment]
@edulanasca since this issues is yet to be assigned, I can work on it

**Comment by Dprof-in-tech** [comment]
hello @edulanasca , I'm Isaac, A fullstack developer with a lot of contributions on Onlydust, I would love to take upon this issue and work on it as fast as possible.

**Comment by Joy-Adah** [comment]
Hi @edulanasca is this issue available? If it is, I'd love to work on it.

**Comment by martinvibes** [comment]
hello @edulanasca can I participate in this issue

**Comment by Dprof-in-tech** [comment]
I'll start working on this today and give feedback as soon as possible.

**Comment by Nadai2010** [comment]
Hello, @Dprof-in-tech we remind you that #ODHack ends tomorrow, please review comments and resolve as soon as possible.

**Comment by danielcdz** [comment]
Hello @gianalarcon is this issue available? I can help if it's possible 🫡

**Comment by gianalarcon** [comment]
All yours! @danielcdz

**Comment by danielcdz** [comment]
@gianalarcon Thank you! I'll be working on it!

**Comment by Supa-mega** [comment]
can i hop on this @edulanasca

**Comment by metalboyrick** [comment]
reopen when needed
