### ISSUE TITLE
fetch ABI from network and add instructions to append into predeployedContracts.ts

### ISSUE THREAD

**Issue by jrcarlos2000** [Scaffold-Stark/scaffold-stark-2#238]
## Issue Overview

Currently users are limited to the `predeployedContracts.ts` provided by default on the monorepo.
We want to allow users to be able to fetch the ABI and receive a prompt on how to append this Contract into their `predeployedContracts` file

After this is achieved, users will be able to download a contract and then use it in the app through the scaffold hooks or use it on the `/debug` page for testing.

## Proposed Solutions or Ideas

Steps :
- add a page next to debug to input an address and fetch the ABI from the network
- parse the Contract with its ABI and add instructions to append into `predeployedContracts.ts`
    - the Abi format fetched from network is different from the one we have, should be able to fix this with a parser function
    - clear insttructions of what to do to append should be written, ( which file, where to append ?, which network )
- implement some good error handling as well

Hints : 
- use functions like [this one](https://www.starknetjs.com/docs/api/classes/providerinterface/#getclassat) to fetch the class of an address through the provider. The class object should contain an ABI element on it.

**Comment by adrianvrj** [comment]
Hey @jrcarlos2000 I have read the steps to achieve this and I think I can manage to complete this task, can I work on it?
