### ISSUE TITLE
Fix yarn deploy --network when fails dont write contracts to nextjs package

### ISSUE THREAD

**Issue by gianalarcon** [Scaffold-Stark/scaffold-stark-2#245]
## Issue Overview

yarn deploy --network mainnet , fails on explorer ( reverted on l2 ) , but seems successful on scaffold scripts. when waiting for transaction receipt on deploy script, need to double check the transaction is successful

[in this line](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/db0128d5c68d054eeb21316cf525ac3132194ebc/packages/snfoundry/scripts-ts/deploy-contract.ts#L239C1-L240C1) , check the status of the tx, to be successful , throw error if not, handle error and dont copy contracts to nextjs

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by Jemiiah** [comment]
I would love to work on this issue too @metalboyrick @gianalarcon
