### ISSUE TITLE
[BUG] useScaffoldContract write bug with external wallets

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#252]
## Issue Overview

Current `useScaffoldContract` contract can only support read operations but not write with extension wallets. We want full functionality of the `Contract` instance of `starknet.js`

## Proposed Solutions or Ideas

- Override `call` function of the contract instance with `parseResponse` as `false` (note that this only works on Bravoos). Argent method TBD

**Comment by adrianvrj** [comment]
Hey can I work on this one?

**Comment by Jemiiah** [comment]
@gianalarcon @metalboyrick seems like your hands are busy may I help work on this issue

**Comment by Jemiiah** [comment]
I would love to work on this issue @metalboyrick @gianalarcon

**Comment by Jemiiah** [comment]
can I be assigned this  to work on this issue @gianalarcon @metalboyrick

**Comment by Supa-mega** [comment]
Can I attempt this issue?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by kayceeDev** [comment]
Is this issue still available?

**Comment by vestor-dev** [comment]
Can I jump on this task?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Acknowledged @metalboyrick 🚀
Will get to it ….

**Comment by Nadai2010** [comment]
Thank you all very much for participating, @ShantelPeters good luck, if you have any questions you can tag us.
