### ISSUE TITLE
Bug: Switch to Starknet Devnet button not working 

### ISSUE THREAD

**Issue by gianalarcon** [Scaffold-Stark/scaffold-stark-2#264]
## Issue Overview

The `Switch to Starknet Devnet` button is not functioning correctly when attempting to switch UI from the Sepolia network to Starknet Devnet.

## Steps to Reproduce

1. Clone this repository.
2. Deploy the contract successfully on the Sepolia network and interact with `YourContract`.
3. Attempt to deploy again, this time targeting Starknet Devnet. To do this, edit the `scaffold.config.ts` file and set Devnet as the target network. 
   - Relevant file: [`scaffold.config.ts`](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/a2974ae8d1132a8889753c9a7602cffdf20b1a9f/packages/nextjs/scaffold.config.ts#L12)
4. Check the UI opened at `http://localhost:3000`. You should see a `wrong network` message.
   - ![wrong network message](https://github.com/user-attachments/assets/908de3cf-584c-49fa-8f91-4d36346f85bd)
5. Attempt to switch to Starknet Devnet using the `Switch to Starknet Devnet` button, but the button doesn't function.
   - ![switch to devnet issue](https://github.com/user-attachments/assets/4528c8e7-6844-4521-8d76-ff00b0f793f1)
6. As a workaround, you can click the `Disconnect` button, then reconnect using the Burnet wallet to switch to the Devnet network.

## Proposed Solution

Fix the bug so that the `Switch to Starknet Devnet` button works as intended. The solution should ensure compatibility with Argent X and Braavos wallets as well.

**Comment by PoulavBhowmick03** [comment]
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community.

Here's how I will solve this

I will address the non-functioning "Switch to Starknet Devnet" button issue as follows:

1. Investigate the current network switching logic in the relevant React component.
2. Update the network switching function to properly handle the switch to Starknet Devnet. This will involve:
   - Using the `getStarknet()` function from the `get-starknet` library to access the Starknet object.
   - Implementing the `wallet_switchStarknetChain` request with the correct chainId for Devnet.
   - Adding proper error handling and user feedback.
3. Ensure the updated logic works with multiple wallet providers, including Argent X and Braavos.
4. Test the solution thoroughly on different networks and with various wallet connections.
5. Update any related documentation or comments in the code to reflect the changes.
6. If necessary, update the UI to provide clearer feedback during the network switching process.

This solution will make the "Switch to Starknet Devnet" button functional and improve the overall user experience when switching networks.

ETA- 1-2 days
I would love to work on this issue

**Comment by Jemiiah** [comment]
hello @gianalarcon I would love to work on this issue I have contributed to this repository before and would still love to do so continually I'll address this issue where the "Switch to Starknet Devnet" button is not functioning correctly when attempting to switch the UI from the Sepolia network to Starknet Devnet, here is a proposed solution based on the information provided:
1. Investigate the Current Network Switching Logic:
i. Examine the relevant React component responsible for network switching.
2. Update Network Switching Function:
i .Modify the network switching function to correctly handle the switch to Starknet Devnet.
ii. Implement the getStarknet() function from the get-starknet library to access the Starknet object.
ii. Utilize the wallet_switchStarknetChain request with the appropriate chainId for Devnet.
iv. Ensure proper error handling and user feedback mechanisms are in place.
3. Compatibility with Wallet Providers:
i. Ensure the updated logic supports multiple wallet providers, including Argent X and Braavos.
4. Thorough Testing:
i. Test the solution rigorously on various networks and with different wallet connections to ensure functionality.
5. Documentation Updates:
i. Update any related documentation or code comments to reflect the changes made in the network switching logic.
6. UI Enhancements:
i. If needed, enhance the UI to provide clearer feedback during the network switching process.
7.Realistically ETA would be 3 days at most but if urgent 2 days i'll say probably

**Comment by ScottyDavies** [comment]
@gianalarcon can you please assign this issue to me?

**Comment by martinvibes** [comment]
hey @gianalarcon i would love to work on this and be a contributor too if i'm giving the chance

#### Check the button’s click handler to ensure it's correctly attached.
#### Review the network switching logic in scaffold.config.ts.
#### Debug the network mismatch detection causing the wrong network message.
#### Test wallet compatibility with Argent X and Braavos.
#### Add console logs to trace the execution flow and identify issues.
#### Compare with the disconnect-reconnect workaround to find differences.
#### Adjust code for correct network parameters and wallet handling.
#### Thoroughly test the fix across different scenarios and wallets.

**Comment by josephchimebuka** [comment]
I would love to contribute to this and fix the error @gianalarcon.  To fix the issue with the "Switch to Starknet Devnet" button, I'll ensure that the button's onClick event is properly connected to the network-switching function and that this function is correctly configured to target Starknet Devnet. I'll add console.log statements to debug the function and verify it's being triggered. Then, I'll make sure that all necessary libraries or configurations for Starknet Devnet are properly set up.

**Comment by ShantelPeters** [comment]
Please can I be assigned

**Comment by ScottyDavies** [comment]
I'm ready to work ASAP, 
ETA 2-5 days @gianalarcon

**Comment by Buuh2511** [comment]
I can fix this. Can i be assigned

**Comment by Jemiiah** [comment]
I can work on this @gianalarcon @jrcarlos2000

**Comment by od-hunter** [comment]
Hi @gianalarcon can I work on this please?
