### ISSUE TITLE
Argent Mobile integration

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#271]
## Issue Overview

Provide Argent Mobile connection with StarknetKit.

Note: current StarknetKit with starknet-react integration does not suppport Starknet React 3. Will push back until we have compatibility with v3.

## Proposed Solutions or Ideas

- Refer to following link for integration reference with starknet-react.

**Comment by ShantelPeters** [comment]
Hi @0xquantum3labs if your hands are tied then I will like to work on this issue
