### ISSUE TITLE
[FEAT] Move "Configure Contracts" to page bottom

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#282]
## Issue Overview

Move the configure contracts tab as shown in the picture.

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/d9e129f4-1956-48cc-beb6-c4c48605dd43">

## Proposed Solutions or Ideas

- Take a look at the components and see how you can move the component on top to the bottom with consistent styling as on the bottom.

**Comment by raizo07** [comment]
Hello @metalboyrick I'll like to work on this.

**Comment by Nadai2010** [comment]
Hello everyone, @raizo07  the Issues for the OD Hack will be assigned to each of you at the start, prepare your skills.

**Comment by Gianfranco99** [comment]
Hello, I would like to work on this issue, since I am already familiar with the repository. I waiting for OD Hack to start!

**Comment by sanieni6** [comment]
Thrilled to contribute this Odhack to the project!

**Comment by vickiddev** [comment]
hello @metalboyrick @Nadai2010 please i would love to work on this issue and be a contributor  on this repo

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by PabloVillaplana** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding Community


### How I plan on tackling this issue
I would like to contribute to this project, because besides the fact that I have been participating in using it, what better way to learn more than by contributing to the project?

**Comment by wugalde19** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi team,
I’m William from Costa Rica 🇨🇷 and a member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as a Full-Stack engineer in several technologies (including the ones used on this project Typescript/JS) and I am currently expanding my expertise in Rust, Cairo, and Solidity.
I also was one of the winners (elite) of the Speedrun & Scaffold challenge/competition.

Profiles:
https://app.onlydust.com/u/wugalde19
https://github.com/wugalde19




### How I plan on tackling this issue
The way I’d approach this is by removing the Configure Contracts option from the menuLinks array in the Header component.
Then in the Footer component add a button or the DownloadContracts component next to the Block Explorer option

I’m interested in learning more about your team and looking forward to contributing to this project.

**Comment by gianalarcon** [comment]
all yours @Gianfranco99 !

**Comment by metalboyrick** [comment]
Hi @Gianfranco99, any updates on this issue?

**Comment by Gianfranco99** [comment]
> Hi @Gianfranco99, any updates on this issue?
Hi, I'll finish today or tomorrow, don't worry! @metalboyrick
