### ISSUE TITLE
[FEAT] Make styles consistent in "Block Explorers" and "Faucet" modals

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#284]
## Issue Overview

When opening the "faucet" and "block explorers windows", the current styles look like this:

<img width="529" alt="image" src="https://github.com/user-attachments/assets/bec8fd62-13f5-4ce8-a1af-5ca18c921510">

Need them to be consistent with the rest of the app.

Reference:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/87d02373-df3c-4352-a772-81d827769bdf">

## Proposed Solutions or Ideas

Update CSS for both components

**Comment by Nadai2010** [comment]
Hello everyone, @mexes20  the Issues for the OD Hack will be assigned to each of you at the start, prepare your skills.

**Comment by vickiddev** [comment]
hello @metalboyrick i am a frontend dev and would love to work on this

this should be to easy to tackle
ETA: 24hrs

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by sasasamaes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
JavaScript developer with 5+ years of experience involved in the full software development lifecycle. My experience includes providing IT solutions for enterprises using JavaScript, React, TypeScript, Node.js, and MongoDB. Additionally, I am expanding my knowledge in Web3 technologies, particularly in Cairo and Solidity.

I am also a community leader and sensei at Dev.f, where I mentor and lead a vibrant community of developers and am a Dojo Coding Member.

My areas of interest include Web3, frontend, backend, and full-stack development.

### How I plan on tackling this issue
Search for the components and change their CSS so that it is consistent with the overall design

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

I have already made a contribution to the open-source ecosystem, and I am eager to engage in more projects, particularly those involving Cairo.

### How I plan on tackling this issue
To address the style inconsistency in the "faucet" and "block explorers" windows, I would start by reviewing the current CSS applied to these components to identify the classes and properties causing the discrepancies compared to the rest of the application.

Next, I would update the CSS for both components to align them with the overall style, including adjustments to margins, paddings, colors, fonts, and any other relevant styles. Additionally, I would ensure that the styles are responsive and maintain a consistent appearance across different devices.

Finally, I would conduct visual tests across various browsers to ensure that the changes are accurately reflected and consistent throughout the application.

**Comment by stephanniegb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I’m Stephanie, a frontend engineer, and I would love to help improve the look of the "faucet" and "block explorers windows",

### How I plan on tackling this issue
My approach
-  I will start by analyzing the existing styles used in the "faucet" and "block explorer" windows to identify discrepancies with the rest of the application.
- I will refer to the design system or style guide to understand the required styles, including colors, fonts, spacing, and component layouts.
- Based on the review, I will update the CSS for the "faucet" and "block explorer" windows to align them with the overall app styling, ensuring consistent use of variables and classes.
- after implementing the changes, I will test the windows across different devices and screen sizes to ensure visual consistency and responsiveness.

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!


I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components. I have worked with figma and zeplin

Feel free to check my onlydust profile here and github profile: lauchaves!


### How I plan on tackling this issue
For this issue, my approach would be:

- Review current styles and compare them to design guidelines.
- Identify inconsistencies in colors, typography, and spacing.
- Update CSS or component styles to match the rest of the app design.
- Ensure consistent button styles and responsive layouts.
- Test changes across different browsers and devices.

**Comment by metalboyrick** [comment]
all yours @stephanniegb !

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
i am a frontend developer with experience in JS and typescript for type safety in js

### How I plan on tackling this issue
i would implement the current page to look like the avaliable screenshot

**Comment by metalboyrick** [comment]
Solved with #296
