### ISSUE TITLE
[CHORE] Migrated Snfoundry package to support starknet foundry script.

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#287]
## Issue Overview

Currently our declare and deploy process uses starknet.js(typescript)

## Proposed Solutions or Ideas

Migrate the declare and deploy process to cairo, you have to use sn-foundry/sncast_std
-  Use scarb 2.8.2
- Use  starknet-devnet 0.2.0
- **You can use latest version of snfoundry**
- Test your solution on Sepolia

Your solution must no break the current features and functionalities of the framework.

**Comment by ScottyDavies** [comment]
@metalboyrick can I be assigned this?

**Comment by Jemiiah** [comment]
when OD hack start I would love to take up this issue @metalboyrick @Nadai2010 @0xquantum3labs @jrcarlos2000

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
With over four years of experience in blockchain development, I have worked across multiple blockchain ecosystems. My expertise spans the entire development lifecycle—from project conceptualization and smart contract design to managing on-chain interactions, seamless protocol integration, and implementing strong security practices.

This enables me to handle both on-chain and off-chain infrastructure, ensuring the development of reliable, scalable blockchain applications.

### How I plan on tackling this issue
I'd start by studying the current configuration and researching how to implement the starknet foundry scripts

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hey @metalboyrick, can i take on this

**Comment by Akinbola247** [comment]
i'd like to work on this

**Comment by gianalarcon** [comment]
All yours @Akinbola247 !
