### ISSUE TITLE
[TEST] Add unit tests for `useScaffoldContract` and `useScaffoldReadContract`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#292]
## Issue Overview

Unit tests required for the indicated hooks to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by od-hunter** [comment]
Hi @metalboyrick Please can I work on this when od hack starts?

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello I'm a frontend and also a blockchain developer and I would love to hop on this issue

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will create unit tests for the `useScaffoldContract` and `useScaffoldReadContract` hooks. The approach will be: 

  

- **I will analyze both hooks** to understand their functionality and interdependencies. 

  

- **I will refer to testing resources** to ensure adherence to best practices in vitest and @testing-library/react. 

  

- **I will establish a testing framework** within a dedicated test file for both hooks. 

  

- **I will develop unit tests**, focusing on: 

  - Core functionalities and their expected outputs. 

  - Testing for error conditions and invalid usage. 

  - Mocking any external dependencies as needed. 

  

- **I will validate the tests locally**, striving for a minimum of 70% code coverage. 

  

- **I will prepare a coverage report screenshot** to accompany my PR.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
i am a frontend developer with experience in developing frontend application developer and testing. kindly assign me 

### How I plan on tackling this issue
Set Up Unit Tests:

I will write unit tests for the hooks using Vitest as the testing framework.
I'll refer to the Vitest documentation for syntax, and if I have experience with Jest, it should be easy to adapt.
Test Hooks:

I will import testing tools from @testing-library/react to specifically test React hooks.
Running Tests:

I'll refer to the project's README.md for instructions on executing tests.
If needed, I can use it.only() to isolate specific tests for debugging but will remove it before submitting the PR.
Mocking and Cross-Device Testing:

I will mock any necessary components or data for the tests and ensure that the tests work across devices, not just on my own.
Ask for Help if Needed:

If I’m unsure about any part of the code or the hooks' functionality, I will check the documentation or ask questions on the issue page or Telegram group.
Code Coverage:

I will aim to achieve at least 70% code coverage for the hooks I am testing. Before submitting the PR, I’ll provide a screenshot of the coverage results to show the achieved percentage.

**Comment by gregemax** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Tell us about your background and how it can be leveraged:

I have experience in JavaScript and testing frameworks, particularly Vitest. I’ve previously written unit tests for React hooks, ensuring code quality and reliability. My familiarity with testing best practices and coverage metrics will enable me to effectively implement comprehensive tests for useScaffoldWriteContract.




### How I plan on tackling this issue
I would start by reviewing the existing hooks to understand their functionality, then write unit tests using Vitest, focusing on edge cases and mocking as needed. I’d ensure the tests achieve at least 70% code coverage and run them to confirm functionality, providing a coverage report with the PR.

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a fullstack dev with experience in writing tests for web applications as well as smart contracts

### How I plan on tackling this issue
I'll start by reviewing the Vitest documentation to familiarize myself with the syntax and best practices for writing unit tests.
Next, I'll identify the specific hooks that need unit tests and compile a list of them.
For each identified hook, I'll write unit tests using Vitest, adhering to its syntax and utilizing @testing-library/react for testing hooks.
I'll follow the instructions in the README.md file to understand how to run the tests.
If I need to isolate specific tests, I'll use it.only() to run those tests individually, but ensure it's removed before submitting the PR.
Where mocking is necessary, I'll implement mocking libraries to avoid dependencies on external factors in the tests.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have a strong background in software development and testing, particularly with React and state management hooks

### How I plan on tackling this issue
To tackle the issue, I would:

Review the hooks' implementation and related documentation to understand their functionality and edge cases.

Set Up Testing Environment: 
Ensure the testing environment is ready by following the README.md instructions for executing tests using Vitest.

Write Tests:
 Create unit tests for each hook, using the appropriate syntax from Vitest and @testing-library/react. Focus on testing various scenarios, including edge cases.

Mock Dependencies: 
Use mocking where necessary to isolate the hooks and ensure tests run consistently across different environments.

Code Coverage: 
Regularly check code coverage during development to ensure it meets the ≥ 70% requirement, providing a screenshot when submitting the PR.

Isolate Tests: 
Utilize it.only() for isolating tests during development, ensuring to remove it before final submission.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello @lukaspetrasek I am Joseph I am a software developer developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. 

### How I plan on tackling this issue
I will start by reviewing the Vitest documentation. 

Then, I will set up the testing environment as outlined in the README.md, including installing @testing-library/react for testing React hooks. I'll proceed by writing unit tests, using it.only() to isolate specific tests for debugging when necessary, and mocking external dependencies to ensure reliable tests. 

Afterward, I will run the tests across different environments or machines to verify they work universally, not just on my device. Once confirmed, I will remove any it.only() instances and submit the PR with passing tests and proper mocking in place.in 3-4 days

**Comment by Nadai2010** [comment]
All yours @CollinsC1O

**Comment by metalboyrick** [comment]
Hi @CollinsC1O , any updates on this issue?

**Comment by CollinsC1O** [comment]
Yes I currently working on it. Had little issues though but it under control now. I will soon send in a pr

**Comment by metalboyrick** [comment]
Hey @CollinsC1O Any updates on this? You can create a draft PR for WIP

**Comment by CollinsC1O** [comment]
hello @metalboyrick yes I've got update. I have implemented most of the unit test both for 'useScaffoldReadContract' and 'useScaffoldContract' and all test cases are passing good both in my local device and outside my device but the challenge I'm facing right now is that when I check for my test coverage it comes up with zero as though there is not test for it. Now I'm wondering if there is a specific direction I should have gone with
