### ISSUE TITLE
[TEST] Add unit tests for `useAutoConnect`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#294]
## Issue Overview

Unit tests required for the indicated hooks to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by ikemHood** [comment]
Hello @metalboyrick, can I work on this

**Comment by vickiddev** [comment]
hello @metalboyrick can  work on this :)

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience, primarily in Next.js. I'm also an active member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I've written numerous unit tests for hooks using Jest, and after reviewing the Vitest documentation, I feel confident in adapting to it smoothly. I'm enthusiastic about learning, contributing, and becoming a part of this project.

### How I plan on tackling this issue
To solve this issue, I would:

Mock necessary hooks:
I would mock useReadLocalStorage, useConnect, and any other dependencies that need mocking to ensure the tests are isolated and focused on the component logic.

Test initial behavior without a saved connector:
I would start by testing the scenario where no connector is saved in local storage. In this case, I would verify that the connect function is not called.

Test with a saved connector:
Next, I would simulate having a saved connector and verify that the appropriate connector is selected from the connectors array. I would also ensure that the connect function is called with the correct arguments.

Test burner wallet logic:
For the burner wallet scenario, I would mock the BurnerConnector type and confirm that the burnerAccount is assigned correctly from burnerAccounts. This would involve testing the branch where the saved connector has an index (ix) and ensuring the correct account is selected.

Ensure full test coverage:
I would verify that all code lines and branches are covered to maintain high test reliability.

Document the tests:
Finally, I would ensure that the test cases are clearly documented for future reference.

**Comment by pablomadrigal** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I’m Pablo Madrigal, I have 7+ years of experience working with React and NextJs. I’m pretty new in the web3 world, I just joined Dojo Coding a couple of weeks ago and have been learning a lot about Cairo and web3 development. Pretty excited to start contributing on Only Dust

### How I plan on tackling this issue
I would create a new test using vitest and very similar to "useDeployedContractInfo" test

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi I would love to work on this issue

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
i am a frontend developer with experience in testing and developing web applications

### How I plan on tackling this issue
I'll start by reviewing the Vitest documentation (https://vitest.dev/) to understand the syntax and best practices for writing unit tests.

Step 2: Identify the hooks to test I'll identify the specific hooks that require unit tests and make a list of them.

Step 3: Write unit tests using Vitest I'll write unit tests for each of the identified hooks using Vitest. I'll make sure to follow the Vitest syntax and use the @testing-library/react hooks testing tools.

Step 4: Execute the tests I'll refer to the README.md file to understand how to execute the tests.

Step 5: Isolate tests when necessary If I need to isolate specific tests, I'll use it.only() to run only those tests. However, I'll make sure to remove it.only() before submitting my PR.

Step 6: Mock when necessary I'll identify situations where mocking is necessary and use mocking libraries to ensure that the tests are not dependent on external factors.

Step 7: Ensure tests are device-agnostic I'll make sure that the tests work not only on my device but also on other devices and environments.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have extensive experience writing unit tests for React hooks using testing libraries such as Vitest and Jest. My familiarity with testing frameworks and mock functions enables me to ensure comprehensive test coverage. I also have experience maintaining high code quality standards and collaborating with teams to streamline testing processes. My expertise will help ensure the accuracy and future stability of the codebase by facilitating easier refactoring and feature validation.




### How I plan on tackling this issue
I would begin by reviewing the relevant hooks and understanding their features from the documentation. Then, I’d write isolated unit tests using Vitest and @testing-library/react, ensuring each hook’s behavior is fully tested. I would mock dependencies where necessary and run tests across different environments to ensure compatibility. I would monitor code coverage and ensure it meets or exceeds the 70% threshold before submitting a PR, providing a screenshot of the coverage for verification.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello @metalboyrick I'm a front-end and also a blockchain developer with experience writing javascript, solidity and cairo

### How I plan on tackling this issue
I can implement good unit tests for `useAutoConnect. testing all its functions

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
i am a frontend developer with background in cario, javascript, typescript etc, i will like to contribute to this ecosystem if even the chance too

### How I plan on tackling this issue
Create unit tests for the specified hooks using Vitest, following the syntax outlined in the [Vitest documentation](https://vitest.dev/). Use the testing utilities from `@testing-library/react`, and refer to `README.md` for running the tests. Ensure to mock dependencies when needed, and isolate tests with `it.only()` while removing it before submitting the PR. Aim for at least 70% code coverage, and provide a screenshot of the coverage report with your submission. If unsure about the features to test, consult the documentation or ask in the issue or Telegram group.

**Comment by Nadai2010** [comment]
All yours @martinvibes

**Comment by metalboyrick** [comment]
Hi @martinvibes , any updates on this issue?

**Comment by martinvibes** [comment]
@metalboyrick @Nadai2010 i will make a PR soon
