### ISSUE TITLE
Update dApp sample, refactor contract

### ISSUE THREAD

**Issue by gianalarcon** [Scaffold-Stark/scaffold-stark-2#300]
## Issue Overview

1. **Update Dependencies:**
   - Upgrade `snforge` to version `0.31.0`.
   - Upgrade `scarb` to version `2.8.3`.
 
2. **Contract Refactor:**
   - Remove `eth_token` from the contract's storage.
   - Replace `IERC20CamelDispatcher` with `IERC20Dispatcher`.

3. **Standardization:**
   - Refactor code to use **snake_case** for calling Cairo entrypoints and functions, replacing any **camelCase** usage in hooks.
  
4. **Test Suite Updates:**
   - Update existing tests to support forks on the `Sepolia` testnet.
   - Add a new Cairo test to verify ERC20 token transfer functionality within the `set_greeting` function of the smart contract.

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by ShantelPeters** [comment]
Hi @gianalarcon  can I please work on this issue

**Comment by Gift-Naomi** [comment]
Can I work on this please?

**Comment by ScottyDavies** [comment]
Hello @gianalarcon can I please be assigned this task?

**Comment by omsant02** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

### How I plan on tackling this issue
I'll start by updating snforge and scarb, then tackle the contract refactor. Removing eth_token and switching to IERC20Dispatcher should be straightforward. The trickiest part might be standardizing to snake_case - I'll use a search tool to speed that up.
For the tests, I'll need to research Sepolia forks first. Adding the new ERC20 transfer test shouldn't be too hard.

**Comment by Buuh2511** [comment]
May i assigned to this issue, i can fix this one

**Comment by omsant02** [comment]
@gianalarcon, I have a question regarding the assignment of this issue. 

Given that it's labeled as ODHack8, the issue could only be assigned to applicants applying through the OnlyDust platform. Could you clarify how it's possible to assign it to Buuh2511? I'm curious to understand the process and ensure we're following the correct procedures for this hackathon.

**Comment by metalboyrick** [comment]
Hey @Buuh2511, any updates on this issue?
