### ISSUE TITLE
Feat: Handle `Option` type as input parameter

### ISSUE THREAD

**Issue by gianalarcon** [Scaffold-Stark/scaffold-stark-2#314]
## Issue Overview

Currently Scaffold stark `Debug` can not handle  `Option` type (Some and None) as input parameter
This is the [testing branch](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/gian/sc-input-option). On this branch the tests use Option and None, and `yarn test` works well.

## Proposed Solutions or Ideas

Explore parsing of this type

**Comment by metalboyrick** [comment]
Adding `Result` to this scope as well

**Comment by metalboyrick** [comment]
Consider if `Enum` that are not primitives are handled here as well.

**Comment by Nadai2010** [comment]
Hi guys, we need the `Option` and `Result`

@Iwueseiter,  @metalboyrick already on this, hopefully for the next OD Hack we will have enough issues for external contributors.

Thanks a lot
