### ISSUE TITLE
`UseScaffoldEventHistory` "Invalid BigInt Syntax"

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#319]
## Issue Overview

![image](https://github.com/user-attachments/assets/f5d461b9-fb74-4489-bc70-fb4caa8b9468)

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by ooochoche** [comment]
Can I do this

**Comment by ooochoche** [comment]
Is this open for contribution

**Comment by akintewe** [comment]
Hello can i be assigned this task

**Comment by od-hunter** [comment]
Hi @metalboyrick , can I work on this please?
