### ISSUE TITLE
invalid input for correct tuple input

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#326]
## Issue Overview

![image](https://github.com/user-attachments/assets/8d1c9a80-befd-44a2-b773-b32a6f6663df)

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

- check out the tuple parser and error handler

**Comment by Iwueseiter** [comment]
Hi @metalboyrick can I work on this?
