### ISSUE TITLE
[FEAT] Create Hook: `useDataTransaction`

### ISSUE THREAD

**Issue by Nadai2010** [Scaffold-Stark/scaffold-stark-2#330]
## Create Hook: `useDataTransaction`

Develop a Hook that provides relevant information obtained from `RpcProvider` from "starknet" regarding transactions. You can refer to the example in the image below as a starting point for [this file](https://github.com/Nadai2010/scaffold-stark-2/blob/d109f31176e7f0a7b8014e24fbdc0ce22ed7736f/packages/nextjs/hooks/scaffold-stark/useScaffoldTx.ts), should always detect the network.

![image](https://github.com/user-attachments/assets/474c926a-a411-4719-a531-fa53695a943f)

## Proposed Solutions or Ideas

You may include information such as:

- Block status
- Block hash
- Starknet version
- Any other data that could be relevant (example TPS, UOPS, Total TX ...) similar explorer Starkscan or Voyager. 

![image](https://github.com/user-attachments/assets/e571126b-0997-4b69-a3ad-63e82027494f)

![image](https://github.com/user-attachments/assets/5462ae8e-0b80-47fc-b1ec-8bbb3e6b7455)

**Comment by Jemiiah** [comment]
@Nadai2010 pls could I work on this issue

**Comment by Nadai2010** [comment]
Hi Jemiah, for now they are just issues to keep the team under control, and it may be done internally, but thanks for being attentive.

**Comment by jedstroke** [comment]
Could I take over this issue?

**Comment by Supa-mega** [comment]
Mind if I try this one?

**Comment by abdegenius** [comment]
May I take care of this?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by cidkagenow** [comment]
Is it okay if I tackle this?

**Comment by ShantelPeters** [comment]
Can I be assigned to this?

**Comment by metalboyrick** [comment]
hey @cidkagenow, i noticed you are already assigned to another issue, per ODHack requirements we cannot have double assignees. Will reassign this issue to someone else since you have already dropped a PR on the other one
