### ISSUE TITLE
[BUG] `0x<blank>` input considered valid on some fields. 

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#345]
## Issue Overview

Fields like `felt252` can accept this input and will still enable the read/send button if the input is `0x[blankl]`. Expected should be disabled button with tooltip.

![image](https://github.com/user-attachments/assets/4f79bc2f-a8da-4a65-b03c-8ace75ffb2db)

## Proposed Solutions or Ideas

either:
- use number input for felt
- check the current input with validation

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

I have already been a contributor to this project on one of the previous odhacks

**Comment by Supa-mega** [comment]
Let me try this one!

**Comment by KevinMB0220** [comment]
Hi, I'm Kevin, I have experience working with Cairo since I'm developing a game with this language and I make contributions from Cairo, for the solution I would review the recommendation and do exhaustive tests to verify that the error is solved.

**Comment by emarc99** [comment]
Could I take a shot at this? I have completed a basecamp and contributed to OD in Cairo. ETA 2 days

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by tasneemtoolba** [comment]
I’d like to work on this. I am familiar with this bug and would like to contribute!!

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by metalboyrick** [comment]
hey @KevinMB0220 , any updates on the issue?

**Comment by KevinMB0220** [comment]
> hey @KevinMB0220 , any updates on the issue?

Hi, I'm still working on the issue, between Wednesday and Thursday I'll have a PR
