### ISSUE TITLE
The wallet you're using to deploy the contract is not deployed in the sepolia network.

### ISSUE THREAD

**Issue by fadyOne** [Scaffold-Stark/scaffold-stark-2#347]
I used Argent Wallet. If you're encountering this issue, try performing multiple transactions between your Sepolia accounts until your accounts appear on https://sepolia.starkscan.co

**Comment by iossocket** [comment]
did you update `packages/nextjs/scaffold.config.ts` and `scaffold-stark-2/packages/snfoundry/.env` before trigger `yarn deploy --network sepolia` ?

**Comment by Nadai2010** [comment]
Hi @fadyOne , do you mean that deploying an account, a contract, or performing write or Multiwrite methods takes time to appear in Sepolia?

It usually depends on the day and the state of the network, it takes longer to be displayed in Starkscan or Voyager than in the Scaffold Stark Debug itself.
