### ISSUE TITLE
Fix in Read Contract ByteArray

### ISSUE THREAD

**Issue by Nadai2010** [Scaffold-Stark/scaffold-stark-2#359]
## Issue Overview

I've been testing the new version and I'm seeing this issue in the YourContract example when deploying.

It doesn't read the `greting` ByteArray or the new `set_greting` correctly.

![imagen](https://github.com/user-attachments/assets/f0cdf520-e5a3-40b7-a6a2-964b49b0f491)

![imagen](https://github.com/user-attachments/assets/a0e941ad-fa25-4b99-bc71-fa175372064a)

**Comment by Iwueseiter** [comment]
@Nadai2010 please I’m ready to work, let me quickly tackle this.

**Comment by Nadai2010** [comment]
Hello good @Iwueseiter , thank you very much, this issue will be assigned internally, it has been created to have it controlled and it can be a bug or punctual, or of the new changes.

In the next OD Hack we will participate, so stay tuned to be able to participate.

**Comment by Iwueseiter** [comment]
Alright.
