### ISSUE TITLE
Дане посилання не працює

### ISSUE THREAD

**Issue by Olexandr88** [Scaffold-Stark/scaffold-stark-2#363]
It is at the bottom of the documentation
configuring [pages/layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts) checkout the Next.js documentation.

**Comment by OWK50GA** [comment]
Can I jump on this?

**Comment by ShantelPeters** [comment]
Hi @Olexandr88 is this open for contribution?

**Comment by OWK50GA** [comment]
Oh, this is an error I think

**Comment by Olexandr88** [comment]
> Hi @Olexandr88 is this open for contribution?

Yes

**Comment by Olexandr88** [comment]
Thanks for the clarification
