### ISSUE TITLE
Automation of performance test

### ISSUE THREAD

**Issue by iossocket** [Scaffold-Stark/scaffold-stark-2#366]
## Issue Overview

Currently, we are using Vercel's Speed Insights tool for performance testing, and the entire testing process is done manually. Is there a way to automate this process, such as adding a GitHub `workflow` or through other automation approaches to implement this automation?

We added `<SpeedInsights />` here, tested locally. but didn't commit it.
```
const ScaffoldStarkApp = ({ children }: { children: React.ReactNode }) => {
  return (
    <html suppressHydrationWarning>
      <body>
        ...
        <SpeedInsights />
      </body>
    </html>
  );
}; 
```

**Comment by estherbreath** [comment]
Can I work on this, please?

**Comment by metalboyrick** [comment]
@iossocket can reopen this issue when ODHack ends
