### ISSUE TITLE
[BUG] Clicking QR button produces a scrollbar, removal needed

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#369]
## Issue Overview

We do not want scroll bar as it causes a layout shift. 

Reproduce:
- Click your wallet
- Click Show QR
- Should feel like it shifted a bit to the side somehow.

(image to be provided soon)

## Proposed Solutions or Ideas

Explore the appropriate CSS

**Comment by vestor-dev** [comment]
Can I try solving this issue?

**Comment by Kingsuite** [comment]
Can I try solving this issue?

**Comment by wheval** [comment]
May I take this issue on?
I would ensure to inspect the styling and replace any fixed width with  dynamic sizing.
I would also hide scrollbar if needed.

ETA is 1 day.

**Comment by caxtonacollins** [comment]
Could I take on this issue?

**Comment by ShantelPeters** [comment]
Could I take on this issue?

**Comment by NueloSE** [comment]
I can handl this task kindly assign me 

ETA <= 24hrs
