### ISSUE TITLE
[FEAT] StarknetID PFP Resolution

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#370]
## Issue Overview

Currently our Address component won't render the NFT PFP for Starknet ID, make it so that it renders the PFP with Starknet API.

## Proposed Solutions or Ideas

- See how to parse user_data field from the starknet ID API and retrieve PFP from there (related PR: https://github.com/Scaffold-Stark/scaffold-stark-2/pull/358)

Starknet ID API Documentation: https://docs.starknet.id/devs/starknetid-api

Would prefer to not use the SDK as to minimalize Dependencies, please consult with the team should you have any further ideas.

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by jedstroke** [comment]
Is this issue still available?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by abdegenius** [comment]
May I pick this up?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by JoE11-y** [comment]
I’d like to work on this.

**Comment by ShantelPeters** [comment]
May I take this issue on?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?
