### ISSUE TITLE
[TEST] Create unit tests `for utils/scaffold-stark/types.ts` file

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#371]
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by Supa-mega** [comment]
May I take care of this?

**Comment by No-bodyq** [comment]
I’d like to resolve this.

**Comment by vestor-dev** [comment]
Mind if I try this one?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by coxmars** [comment]
I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

1- I will review the project structure to place the tests as expected.
2- I’m going to use the code structure/best practices implemented among the project codebase to continue the standard
3- I'm going to add the unit tests passing with >= 70 % code coverage.

Here I applied unit tests with Vitest: https://github.com/ArkProjectNFTs/ark-market/pull/181

ET: 3 days

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by coxmars** [comment]
I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

1- I will review the project structure to place the tests and other parts as expected.
2- I’m going to use the code structure/best practices implemented among the project codebase to continue the standard
3- I'm going to add the unit tests passing >= 70 % code coverage.

I implemented the same here: https://github.com/ArkProjectNFTs/ark-market/pull/181

ET: 3 days

**Comment by ShantelPeters** [comment]
I’d like to work on this.

**Comment by ryzen-xp** [comment]
Is this issue still available?

**Comment by NueloSE** [comment]
am a software developer with experience in create web applications and writing test to ensure proper functionality of these applications.
I have handled similar issue in past odhack 

check the link to similar [task](https://github.com/Scaffold-Stark/scaffold-stark-2/pull/316)

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue
