### ISSUE TITLE
[TEST] Create unit tests for `utils/scaffold-stark/common.ts` file

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#372]
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by BraCR10** [comment]
Hello maintainers I am BRACR10 from the community of DOJO Coding, I would like to do this unit test, I have experience with TypeScript and unit tests using Jest, to handle this issue I plan to correctly implement the environment needed for testing  and then testing the functions in the file. Then I will report the results and problems that I find.

**Comment by vestor-dev** [comment]
I'd love to give this a go.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by abdegenius** [comment]
Could I take on this issue?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by CollinsC1O** [comment]
I will love to work on this. Please assign

**Comment by ShantelPeters** [comment]
I’d love to work on this task.

**Comment by ryzen-xp** [comment]
May I take this issue on?

**Comment by NueloSE** [comment]
am a software developer with experience in create web applications and writing test to ensure proper functionality of these applications.
I have handled similar issue in past odhack 

check the link to similar [task](https://github.com/Scaffold-Stark/scaffold-stark-2/pull/316)

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I am good with tests and I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo
I have gone through the proposed solution and I’ll say I’m up for the task, I’ll make sure to keep you updated at all times and ask any questions if I have. Also, in my PR, I’ll make sure to provide a screenshot of the coverage for the specific units I am working on.

Kindly assign me please.
