### ISSUE TITLE
[TEST] Create unit tests for `utils/scaffold-stark/contract.ts` file

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#373]
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by CollinsC1O** [comment]
I'd love to work on this!

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I am good with tests and I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo
I have gone through the proposed solution and I’ll say I’m up for the task, I’ll make sure to keep you updated at all times and ask any questions if I have. Also, in my PR, I’ll make sure to provide a screenshot of the coverage for the specific units I am working on.

Kindly assign me please.

**Comment by Supa-mega** [comment]
Could I be assigned to this?

**Comment by petersdt** [comment]
May I take this issue on?

**Comment by No-bodyq** [comment]
Could I try solving this?

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by vestor-dev** [comment]
Can I work on this, please?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by abdegenius** [comment]
May I take care of this?

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by caxtonacollins** [comment]
I will love to start working on this. Please assign me.

**Comment by ShantelPeters** [comment]
Can I contribute to this one?

**Comment by NueloSE** [comment]
am a software developer with experience in create web applications and writing test to ensure proper functionality of these applications.
I have handled similar issue in past odhack 

check the link to similar [task](https://github.com/Scaffold-Stark/scaffold-stark-2/pull/316)

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by od-hunter** [comment]
@metalboyrick Acknowledged, I'll open a pr soon

**Comment by Nadai2010** [comment]
Thank you all very much for participating, @od-hunter good luck, if you have any questions you can tag us.
