### ISSUE TITLE
[TEST] Create unit tests for `useTargetNetwork.ts` 

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#374]
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by CollinsC1O** [comment]
Is this issue still available?

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I am good with tests and I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo
I have gone through the proposed solution and I’ll say I’m up for the task, I’ll make sure to keep you updated at all times and ask any questions if I have.

Kindly assign me please.

Ps: I can't seem to apply for this issue via onlydust

**Comment by Supa-mega** [comment]
Is this issue still available?

**Comment by No-bodyq** [comment]
Could I grab this task?

**Comment by vestor-dev** [comment]
I’d like to resolve this.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!  Can I attempt this issue?

**Comment by Kaminar-i** [comment]
Can I be assigned this issue

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I will create unit tests for useTargetNetwork.ts using Vitest as the testing framework, ensuring >= 70% code coverage. I'll mock where necessary, follow proper test isolation using it.only(), and provide a screenshot of the coverage in the PR.

Please assign this to me. Thank you!

**Comment by NueloSE** [comment]
am a software developer with experience in create web applications and writing test to ensure proper functionality of these applications.
I have handled similar issue in past odhack 

check the link to similar [task](https://github.com/Scaffold-Stark/scaffold-stark-2/pull/316)

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue
