### ISSUE TITLE
[CHORE] Update tool versions , Scarb and starknet-foundry, cairo, devnet-rs

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#375]
## Issue Overview

Update the dependencies to latest version.

## Proposed Solutions or Ideas

- Update the dependency first
- Fix the broken parts
- Run unit tests for smoke check
- Try out the affected components to ensure that it is as functioning as before

Kindly test it first before requesting for review

**Comment by Jake1698** [comment]
Can I try this one?

**Comment by beeguy74** [comment]
Hi, I am a beginner Cairo developer from Paris. 
Closed 2 tasks on cairo on 10 ODHACK. Solved dependency mismatch problems.
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and do the PR within 48 hours.
May I pick this up?
May I try my hand at this?

**Comment by GideonBature** [comment]
Could I be assigned to this?

Could I be assigned to this?

My name is Gideon Bature, a Software Engineer, I have experience working with Cairo: updating codebase written in cairo, fixing broken parts and ensuring the code is not broken by the update. If given the opportunity, I will send my first PR within 48 hours.

Thank you!

**Comment by Supa-mega** [comment]
Would love to tackle this!

**Comment by wheval** [comment]
I'd love to work on this!. Please Assign

ETA is 1 day.

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo

I have gone through the proposed solution and I promise to update the dependency first, fix the broken parts, run unit tests for smoke check and try out the affected components to ensure that it is as functioning as before. I’ll also make sure to test it first before requesting for review.

Kindly assign me please

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by abdegenius** [comment]
Mind if I try this one?

**Comment by tasneemtoolba** [comment]
Is it okay if I take this? I checked previous similar issues in other starknet projects, and familiar with scaffold-stark.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by Emmanex01** [comment]
I’d like to resolve this.

**Comment by caxtonacollins** [comment]
May I take care of this?

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?
