### ISSUE TITLE
[REFACTOR] Refactor `0x${somedata.toString(16)}` to use `feltToHex` 

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#376]
## Issue Overview

Refactor instances where we have these long expressions to use `feltToHex`, they do the same thing.

## Proposed Solutions or Ideas

- Replace the functions
- Make sure unit tests pass !

**Comment by GideonBature** [comment]
Can I handle this task?

Could I be assigned to this?

My name is Gideon Bature, a Software Engineer, I have experience working with Cairo, refactoring, updating, building unit and integration tests where necessary. If given the opportunity, I will send my first PR within 48 hours.

Thank you!

**Comment by abdegenius** [comment]
Is it okay if I tackle this?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Tzienom** [comment]
Hi. I would love to work on this issue.

**Comment by ShantelPeters** [comment]
I'd be happy to do this.

**Comment by TheSQLguy** [comment]
To address this issue, I would factorise long expressions to use feltToHex wherever possible; make sure all affected code is updated and run some unit tests to confirm nothing else breaks; submit for review.

**Comment by omsant02** [comment]
I'd like to help refactor the toString(16) expressions to use feltToHex. I can review the codebase for these instances, replace them with the more readable feltToHex function, and ensure all unit tests pass after the changes.

ETA : 12 hrs
