### ISSUE TITLE
[CHORE] Add `isFork` to the `scaffold.config.ts`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#378]
## Issue Overview

Add tag for fork (you can call it `isFork`) on `scaffold.config.ts` and don't show wrong network dropdown if fork is true. refer to this PR for more context: https://github.com/Scaffold-Stark/scaffold-stark-2/pull/320/files

## Proposed Solutions or Ideas

- Add the property in `scaffold.config.ts`
- Something to note: the chain ID of a fork is the same as the target network. i.e. if you are on a fork of mainnet, your chain id is MAINNET_CHAINID and your RPC url is localhost. This can cause some issues which lead to `wrong network` currently, because the framework expects localhost rpc to be = devnet.
- *make sure services that depend on network are working properly : conditionals like starknet id, faucet*, a fork is same as devnet but with a different chain id

**Comment by MooreTheAnalyst** [comment]
Can I jump on this task?
In scaffold.config.ts, i will add a new boolean property isFork and set it to true when running on a forked network, then update the logic for displaying the wrong network dropdown to check this property, and skip rendering the dropdown if isFork is true.

**Comment by Supa-mega** [comment]
Can I take this issue?

**Comment by petersdt** [comment]
I’m interested in this one.

**Comment by jedstroke** [comment]
Let me try this one!

**Comment by raizo07** [comment]
I'd like to take this issue. I'm a Software developer with over 3 years experience

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo
I have gone through the pr and I’ll say I’m up for the task and I’ll ask more questions if I have any.

Kindly assign me please.

**Comment by NowGoody** [comment]
Can I take care of this issue?

**Comment by abdegenius** [comment]
I’d love to work on this task.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by aniruddhaaps** [comment]
To solve this problem:

I would add an isFork property in scaffold.config.ts. Set it appropriately based on requirement.
Then update the logic driving the network dropdown so that it does not show when isFork is true.
See the linked PR for implementation context and align changes with existing codebase.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Down to handle this task.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by kayceeDev** [comment]
I'd love to work on this!

**Comment by ShantelPeters** [comment]
Could I try solving this?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by vestor-dev** [comment]
Can I try solving this issue?

**Comment by TheSQLguy** [comment]
To solve this problem:

I would add an isFork property in scaffold.config.ts. Set it appropriately based on requirement.
Then update the logic driving the network dropdown so that it does not show when isFork is true.
See the linked PR for implementation context and align changes with existing codebase.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by raizo07** [comment]
@metalboyrick Acknowledged, on it.

**Comment by metalboyrick** [comment]
hey @raizo07 , any updates on the issue?

**Comment by raizo07** [comment]
@metalboyrick yes, sending a PR soon.
