### ISSUE TITLE
[TEST] Create unit tests of `useScaffoldStarkProfile.ts`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#379]
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by raizo07** [comment]
@metalboyrick can I work on this?

**Comment by fabrobles92** [comment]
Hello Fab here,

I work as a Full Stack using Python and JavaScript frameworks such as React and Vue where I have created unit and integrations tests with its corresponding mocks using Jest in my day to day work. I usually structure the unit tests using AAA approach (Arrange, Act, Assert).

With that in mind I think this can be easily tackled and I would love to contribute for the first time to this project :)

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by jedstroke** [comment]
Can I work on this, please?

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I am good with tests and I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo
I have gone through the proposed solution and I’ll say I’m up for the task, I’ll make sure to keep you updated at all times and ask any questions if I have.

Kindly assign me please.

**Comment by CollinsC1O** [comment]
Hello @metalboyrick May I take this issue on?

**Comment by No-bodyq** [comment]
May I take this issue on?

**Comment by abdegenius** [comment]
Would love to tackle this!

**Comment by aniruddhaaps** [comment]
To address the problem, I would

Use Vitest for unit tests and refer to the documentation of Vitest for syntax.

Then import hooks testing utilities from @testing-library/react along with mock dependencies.

Clear, portable tests: Validate across devices. Ensure it.only() is removed before submission of the PR.

**Comment by gadyrcdz** [comment]
Let me handle this issue! I want to learn more about these issues and this one gonna help me a lot. Also, I'm a member of the community Dojo Coding.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Down to handle this task.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects)

**Comment by lauchaves** [comment]
Hey! I'm Lau Chaves, I would like to contribute to this issue!

I have over 5 years of experience with JavaScript, ReactJS,React Native TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica. 

Id follow the instructions mentioned above to do the tests :)

**Comment by cidkagenow** [comment]
I’d like to work on this.

**Comment by Kaminar-i** [comment]
Could I take a shot at this?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by ryzen-xp** [comment]
Hi, I'm a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Vitest, and web development. I'll create unit tests for useScaffoldStarkProfile.ts using Vitest, ensuring >= 70% code coverage. I'll handle necessary mocking and will provide a screenshot of the coverage in the PR.

Please assign this to me. Thank you!

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
To address the problem, I would

Use Vitest for unit tests and refer to the documentation of Vitest for syntax.

Then import hooks testing utilities from @testing-library/react along with mock dependencies.

Clear, portable tests: Validate across devices. Ensure it.only() is removed before submission of the PR.

**Comment by NueloSE** [comment]
am a software developer with experience in create web applications and writing test to ensure proper functionality of these applications.
I have handled similar issue in past odhack 

check the link to similar [task](https://github.com/Scaffold-Stark/scaffold-stark-2/pull/316)

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by error-xp** [comment]
Can I attempt this issue?

**Comment by lauchaves** [comment]
Thanks will open a PR soon 🚀

**Comment by Nadai2010** [comment]
Thank you all very much for participating, @lauchaves good luck, if you have any questions you can tag us.

**Comment by lauchaves** [comment]
@Nadai2010 hey left a question on the pr, may u take a look? 😄
