### ISSUE TITLE
[TEST] Create unit tests for `useTransactor.ts`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#380]
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by vestor-dev** [comment]
May I handle this issue?

**Comment by CollinsC1O** [comment]
May I be assigned to this?

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by jedstroke** [comment]
May I take care of this?

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I am good with tests and I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo
I have gone through the proposed solution and I’ll say I’m up for the task, I’ll make sure to keep you updated at all times and ask any questions if I have.

Kindly assign me please.

**Comment by Luluameh** [comment]
Hi, I’m a frontend developer with experience in TypeScript and testing frameworks like Vitest and Jest. I’m confident in my ability to write unit tests for the useTransactor.ts hook to improve the reliability and maintainability of the codebase.

Plan to Solve the Issue:

Review the useTransactor.ts file to understand the hook’s functionality and behavior.
Identify key features and edge cases that should be tested, such as state changes, side effects, and interactions with external dependencies.
Implement unit tests using Vitest, following the syntax and documentation.
Mock any necessary functions or components to isolate the hook and ensure the tests focus on the hook’s logic.
Ensure all tests are platform-independent and run successfully on multiple devices.
Achieve >= 70% code coverage, as specified, and provide a screenshot of the coverage report when submitting the PR.
Follow up on test execution instructions from the README.md and ensure that tests pass consistently.
Estimated Completion Time: 2 days

I’m excited to contribute by ensuring this hook is well-tested and future-proof. Looking forward to collaborating!

**Comment by aniruddhaaps** [comment]
To write unit tests for the file, I would

Use Vitest for test cases, referring to Vitest documentation for syntax.

Then import the necessary hooks testing tools from @testing-library/react with dependency mocking according to portability standards.

Finally testing the features thoroughly, using documentation or asking for help if needed, and ensure the tests pass on all devices before submitting the PR.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by abdegenius** [comment]
Could I take over this issue?

**Comment by caxtonacollins** [comment]
Let me try this one!

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Down to handle this task.

**Comment by 3th-Enjay** [comment]
Can I jump on this task?

**Comment by kayceeDev** [comment]
I'd like to take this issue.

**Comment by psychemist** [comment]
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive experience testing backend systems and smart contracts using Jest, Mocha, Chai, and Forge. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

i would test the useTransactor.ts hook by:

- Studying the code to map out its core functions and dependencies and identify relevant test conditions and edge cases
- Writing Vitest scripts to test the hook's logic, making sure to cover all functions
- Mocking the hook's behaviour where necessary to achieve 70% code coverage at minimum
- Ensure that the tests work across all platforms and not just on my local machine
- Include a screenshot alongside my PR submission

I aim to complete this task within 2 days of being assigned and setting up my development environment.

Thank you for the opportunity and I look forward to working with you.

**Comment by ShantelPeters** [comment]
I'd love to give this a go.

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by MarcusDavidG** [comment]
Can I hop on  this issue?

**Comment by ryzen-xp** [comment]
Hi, I'm a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I'll create unit tests for useTransactor.ts using Vitest, ensuring >= 70% code coverage and handling mocking as needed. I'll also provide a screenshot of the coverage in the PR.

Please assign this to me. Thank you!

**Comment by TheSQLguy** [comment]
To write unit tests for the file, I would

Use Vitest for test cases, referring to Vitest documentation for syntax.

Then import the necessary hooks testing tools from @testing-library/react with dependency mocking according to portability standards.

Finally testing the features thoroughly, using documentation or asking for help if needed, and ensure the tests pass on all devices before submitting the PR.

**Comment by NueloSE** [comment]
am a software developer with experience in create web applications and writing test to ensure proper functionality of these applications.
I have handled similar issue in past odhack 

check the link to similar [task](https://github.com/Scaffold-Stark/scaffold-stark-2/pull/316)

**Comment by jsanchez556** [comment]
Hello, my name is Jose Mario, and I am from Costa Rica. I am a full-stack developer with more than 15 years of experience. Since the version 7.0, I've actively participated in the ODHacks driven by my work with Dojo Coding, the largest community of blockchain and Web3 developers in the country, and I have extensive experience in developing tests for backend systems using technologies like Mocha, Jest, Sinon, Chai, among others.

How to approach the solution:

1. Go through file functionality and documentation, clear doubts on the git issue page or the Telegram group.
2. Vitest and @testing-library/react: Check the instructions in README.md.
3. Identify key features, edge cases, and dependencies. If necessary, mock out any external API or hooks.
4. Write tests using the syntax from Vitest (describe, it, expect), strive for ≥70% code coverage; make sure tests run well across different environments.
5. Run tests with coverage and attach screenshot

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue
