### ISSUE TITLE
[CHORE] House Cleaning

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#381]
## Issue Overview

A bunch of tasks to clean up the codebase
- Remove `.gitmodules` file
- Check for `CONTRIBUTING.md` and `README.md` to ensure they are up to date

**Comment by GideonBature** [comment]
I'd love to work on this!

Could I be assigned to this?

My name is Gideon Bature, a Software Engineer, I have experience documenting codes both on the frontend and backend. I have worked and contributed various documentations. If given the opportunity, I will send my first PR within 72 hours.

Thank you!

**Comment by jedstroke** [comment]
I'd like to handle this task.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by abdegenius** [comment]
I’d love to work on this task.

**Comment by Cisco-A** [comment]
Would love to tackle this!

**Comment by caxtonacollins** [comment]
Could I take on this issue? please, am ready to put in the work

**Comment by chigozzdevv** [comment]
Hello, good day :)
Please can I help you clean up your codebase?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by MarcusDavidG** [comment]
Very ready to take this issue?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

i'm willingly going to do this even if it is not rewarded kindly assign :)

**Comment by omsant02** [comment]
I'd like to help clean up the codebase. I can verify and remove the outdated .gitmodules file, then update both documentation files to reflect current setup requirements and compatible versions. I have experience with Starknet development and can ensure the changes maintain consistency across the project.

ETA : 1 day

**Comment by BrunoAmbricca** [comment]
Can I be assigned to this?

**Comment by metalboyrick** [comment]
hey @BrunoAmbricca , any updates on the issue?

**Comment by Nadai2010** [comment]
Hi @BrunoAmbricca looking forward to your PR, remember that the ODHack will finish on Sunday.

**Comment by BrunoAmbricca** [comment]
Hi @Nadai2010 I´ll make the PR today.
