### ISSUE TITLE
Discrepancies in documentation

### ISSUE THREAD

**Issue by l-henri** [Scaffold-Stark/scaffold-stark-2#406]
## Issue Overview

Installation instructions on https://docs.scaffoldstark.com/ do not correspond to what is needed to run the repo correctly

## Proposed Solutions or Ideas

Correct version numbers on https://docs.scaffoldstark.com/quick-start/installation#install-scarb
Move to scarb 2.9.2

**Comment by gianalarcon** [comment]
Thanks for notifying us, fix should be live now!
